[initfs] Change hw-ramdisk into a set of tools for generating initrds
The old way of extracting and adding manually files to initrd based on
mer-ramdisk does not scale well when we need to add binaries with library
dependencies to any given initrd.

Replaced the old ready made ramdisk cpio archive with set of initrd
creation tools based on moslo project. These tools can be used to
generate the initrd in any downstream project by providing a list of
files that are needed. The tools will automatically add right
versions of needed libraries to the initrd to make sure your binary
tools always work.

The template contains already busybox-static with symlinks added, so
in simplest case you only provide your init script to the tools
and combine the final rootfs.cpio.gz with your kernel zImage.

The sequence to create a initrd contains now 2 steps:
1. initialize-ramdisk.sh
   * Initialize needed directories and file lists for moslo-build
2. moslo-build.sh
   * Build the initrd based on files in initfs/skeleton/ and given params

Signed-off-by: Kalle Jokiniemi <kalle.jokiniemi@jolla.com>

diff --git a/initfs/skeleton/init b/initfs/skeleton/init
--- a/initfs/skeleton/init
+++ b/initfs/skeleton/init
@@ -25,13 +25,11 @@
 # Location of the device init script, if not set, few defaults are tried.
 INITBIN=/sbin/preinit
 
+# What to mount as rootfs
+ROOTDEV="/dev/mmcblk1p1"
+
 # Where to mount the rootfs
 ROOTMNTDIR="/rootfs"
-
-# With MNTSCRIPT, you can use your own mounting script and bypass the default
-# root mounting. The script should take $ROOTMNTDIR as parameter
-# for where to mount the root.
-MNTSCRIPT="/sbin/root-mount"
 
 fail() {
     echo "Failed"
@@ -40,27 +38,16 @@ fail() {
 }
 
 echo "Starting ramdisk.."
-mkdir -p /proc
-mount -t proc proc /proc
-
-mkdir -p /sys
-mount -t sysfs sys /sys
-
-mkdir -p /dev
-mount -t devtmpfs devtmpfs /dev
+mount -a
 
 mkdir -p $ROOTMNTDIR
 
 # Mount the root filesystem
-if [ -e $MNTSCRIPT ]; then
-	$MNTSCRIPT $ROOTMNTDIR
-	if [ $? -eq 0 ]; then
-		echo "Mounting root succeeded"
-	else
-		fail "Mouting root failed"
-	fi
+mount $ROOTDEV $ROOTMNTDIR
+if [ $? -eq 0 ]; then
+	echo "Mounting root succeeded"
 else
-	fail "$MNTSCRIPT does not exist, cannot mount root!"
+	fail "Mouting root failed"
 fi
 
 echo "Searching for init process..."
@@ -79,9 +66,7 @@ fi
 
 # umount everything before doing switch root as the init process
 # is responsible of doing these inside the final boot env.
-umount -l /dev
-umount -l /sys
-umount -l /proc
+umount -a
 
 echo "Switching to rootfs at ${ROOTMNTDIR}, with init ${INITBIN}"
 
